services:
  database:
    command:
    - --character-set-server=utf8mb4
    - --collation-server=utf8mb4_unicode_ci
    - --skip-character-set-client-handshake
    - --skip-innodb-read-only-compressed
    container_name: mariadb-database-two
    environment:
      MYSQL_ROOT_PASSWORD: osboxes.org
    healthcheck:
      test:
      - CMD-SHELL
      - mysqladmin ping -h localhost --password=osboxes.org
      interval: 1s
      retries: 20
    image: mariadb:10.6
    networks:
      mariadb-network: null
    restart: unless-stopped
    volumes:
    - type: bind
      source: /home/frappe/frappe_docker/mariadb-two/var-lib-mysql
      target: /var/lib/mysql
networks:
  mariadb-network:
    name: mariadb-network
volumes:
  db-data:
